### ISSUE TITLE
Bad code habit

### ISSUE THREAD

**Issue by MrTroble** [Der-Zauberer/DeskPlaner#2]
Don't use unnecessary constructors!

Better way is to extend Stage
Like:
```java
public class Console extends Stage {
```

https://github.com/Der-Zauberer/DeskPlaner/blob/5c5b5cbbe7b36870feeccdabc8aefb02bcf7e79b/src/deskplaner/util/Console.java#L14-L62

**Comment by MrTroble** [comment]
Other idea: Doing it in procedural code style -> static method

**Comment by Der-Zauberer** [comment]
I used the first idea with `extends Stage`

**Comment by MrTroble** [comment]
There is even more bad code habit ... but it seams you are cleaning it up ... getting better
