### ISSUE TITLE
Better to extend Dialog or Alert

### ISSUE THREAD

**Issue by MrTroble** [Der-Zauberer/DeskPlaner#3]
https://github.com/Der-Zauberer/DeskPlaner/blob/152976503da85b1fda6c0022a10c96391abbcf64/src/deskplaner/util/DeskDialog.java#L18

https://github.com/Der-Zauberer/DeskPlaner/blob/152976503da85b1fda6c0022a10c96391abbcf64/src/deskplaner/util/DeskDialog.java#L20 Already exists as in AlertType

https://github.com/Der-Zauberer/DeskPlaner/blob/152976503da85b1fda6c0022a10c96391abbcf64/src/deskplaner/util/DeskDialog.java#L21 Already exists as in ButtonType

https://github.com/Der-Zauberer/DeskPlaner/blob/152976503da85b1fda6c0022a10c96391abbcf64/src/deskplaner/util/DeskDialog.java#L103-L138
The complete section is already given by the Dialog/Alert callback
As follows:
```java
alert.showAndWait().filter(type-> type.equals(ButtonType.OK)).ifPresent(type -> {
        	//do smthn
});
```

ButtonTypes are addable/removable by
```java
alert.getButtonTypes().addAll(ButtonType.APPLY, ButtonType.CANCEL);
```

**Comment by MrTroble** [comment]
for additional info 
https://docs.oracle.com/javase/8/javafx/api/javafx/scene/control/Dialog.html
https://docs.oracle.com/javase/8/javafx/api/javafx/scene/control/Alert.html

**Comment by Der-Zauberer** [comment]
I will work on that in the next few days.

**Comment by Der-Zauberer** [comment]
Closed because of code rewrite.
